import React from "react"
import "./CreatorRewards.css"
import { CREATOR_ADDRESS } from "../utils/pumpfun"
import { useCreatorRewards } from "../hooks/useCreatorRewards"

const solFormatter = new Intl.NumberFormat("en-US", {
  minimumFractionDigits: 2,
  maximumFractionDigits: 4,
})

const usdFormatter = new Intl.NumberFormat("en-US", {
  style: "currency",
  currency: "USD",
  maximumFractionDigits: 0,
})

const integerFormatter = new Intl.NumberFormat("en-US")

const shorten = (value = "") => {
  if (value.length <= 12) return value
  return `${value.slice(0, 6)}…${value.slice(-4)}`
}

const COIN_ADDRESS = "99dkd8uWbAPF4yjKBU42mxd8BP9bJMybuGkyb6Hapump"

const CreatorRewards = () => {
  const {
    rewardData,
    loading,
    isRefreshing,
    error,
    lastUpdated,
    refresh,
  } = useCreatorRewards()

  const renderValue = (value, formatter) => {
    if (loading || value == null) {
      return <span className="creator-rewards__skeleton" />
    }

    return formatter.format(value)
  }

  return (
    <section id="creator-rewards" className="creator-rewards">
      <div className="creator-rewards__container">
        <div className="creator-rewards__heading">
          <p className="creator-rewards__eyebrow">Live Creator Rewards</p>
          <h2>Dev Wallet Fee Tracker</h2>
          <p className="creator-rewards__description">
            Real-time fees generated by the Official Santa Claus Coin dev wallet
            straight from Pump.fun. Updates automatically every 30 seconds so
            you always know how much the elves have stacked.
          </p>
        </div>

        <div className="creator-rewards__grid">
          <div className="creator-rewards__card creator-rewards__card--primary">
            <div className="creator-rewards__card-top">
              <span>Total Fees Collected</span>
              <span className="creator-rewards__live-pill">
                <span
                  className={`creator-rewards__live-dot ${isRefreshing ? "pulsing" : ""}`}
                />
                Live
              </span>
            </div>
            <div className="creator-rewards__value">
              {renderValue(rewardData.sol, solFormatter)}
              {!loading && rewardData.sol != null && (
                <span className="creator-rewards__value-suffix">SOL</span>
              )}
            </div>
            <div className="creator-rewards__subvalue">
              {!loading && rewardData.usd != null && usdFormatter.format(rewardData.usd)}
              {loading && <span className="creator-rewards__skeleton" />}
            </div>
            <p className="creator-rewards__meta">
              Data source:{" "}
              <a
                href="https://swap-api.pump.fun"
                target="_blank"
                rel="noreferrer"
              >
                swap-api.pump.fun
              </a>
            </p>
          </div>

          <div className="creator-rewards__card creator-rewards__card--secondary">
            <h3>Wallet Snapshot</h3>
            <div className="creator-rewards__detail-row">
              <span>Creator wallet</span>
              <code>{shorten(CREATOR_ADDRESS)}</code>
            </div>
            <div className="creator-rewards__detail-row">
              <span>Official coin</span>
              <code>{shorten(COIN_ADDRESS)}</code>
            </div>
            <div className="creator-rewards__detail-row">
              <span>Fees (lamports)</span>
              <strong>
                {renderValue(
                  rewardData.lamports ? Number(rewardData.lamports) : null,
                  integerFormatter
                )}
              </strong>
            </div>
            <div className="creator-rewards__actions">
              <a
                href="https://pump.fun/profile/5LAokPTr67hxMzDTEqjKcbc2SY34W7TmTqe9hdyEzNqg?tab=coins"
                target="_blank"
                rel="noreferrer"
                className="creator-rewards__link"
              >
                View on Pump.fun
              </a>
              <button
                type="button"
                className="creator-rewards__refresh-btn"
                onClick={refresh}
                disabled={loading || isRefreshing}
              >
                {isRefreshing ? "Refreshing…" : "Refresh now"}
              </button>
            </div>
            {lastUpdated && (
              <p className="creator-rewards__timestamp">
                Last updated {lastUpdated.toLocaleTimeString()}
              </p>
            )}
          </div>
        </div>

        {error && <p className="creator-rewards__error">{error}</p>}
      </div>
    </section>
  )
}

export default CreatorRewards

